#!/usr/bin/env python3
"""
Run a CUDA executable on the `raw` dataset in an HDF5 file, create its output,
and calculate MSE, PSNR, SSIM, maximum absolute error, output min, and output max.

The CUDA executable must accept an input raw-file path and an output raw-file
path. Use --cuda-command to describe its command-line interface.

Examples
--------
Executable syntax:
    ./renderer input.raw output.raw 512 512 512

Run:
    python run_cuda_and_evaluate.py \
        --reference volume.h5 \
        --reference-key raw \
        --cuda-command "./renderer {input} {output} {dim0} {dim1} {dim2}" \
        --output cuda_output.raw \
        --output-dtype float32

Executable syntax:
    ./renderer --input input.raw --output output.raw

Run:
    python run_cuda_and_evaluate.py \
        --reference volume.h5 \
        --reference-key raw \
        --cuda-command "./renderer --input {input} --output {output}" \
        --output cuda_output.raw
"""

from __future__ import annotations

import argparse
import json
import math
import shlex
import subprocess
import tempfile
from pathlib import Path
from typing import Any

import h5py
import numpy as np
from skimage.metrics import structural_similarity


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run CUDA code on an H5 dataset and evaluate its output."
    )
    parser.add_argument("--reference", required=True, type=Path)
    parser.add_argument("--reference-key", default="raw")
    parser.add_argument(
        "--cuda-command",
        required=True,
        help=(
            "CUDA command template. Available placeholders: "
            "{input}, {output}, {dim0}, {dim1}, {dim2}, {dim3}, {size}, {dtype}."
        ),
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Output file that the CUDA executable will create.",
    )
    parser.add_argument(
        "--input-dtype",
        default=None,
        help="Datatype written to the temporary CUDA input. Default: H5 datatype.",
    )
    parser.add_argument(
        "--output-dtype",
        default="float32",
        help="Datatype generated by CUDA. Default: float32.",
    )
    parser.add_argument(
        "--output-shape",
        nargs="+",
        type=int,
        default=None,
        help="Output shape. Default: same shape as the H5 raw dataset.",
    )
    parser.add_argument(
        "--data-range",
        type=float,
        default=None,
        help="PSNR/SSIM range. Default: reference max minus reference min.",
    )
    parser.add_argument(
        "--ssim-mode",
        choices=("slice", "volume"),
        default="slice",
    )
    parser.add_argument("--save-json", type=Path, default=None)
    parser.add_argument(
        "--keep-input-raw",
        type=Path,
        default=None,
        help="Keep the extracted H5 dataset at this raw-file path.",
    )
    return parser.parse_args()


def load_h5_dataset(path: Path, key: str) -> np.ndarray:
    if not path.exists():
        raise FileNotFoundError(f"Reference file not found: {path}")

    with h5py.File(path, "r") as file:
        normalized_key = key.lstrip("/")
        if normalized_key not in file:
            available: list[str] = []

            def visitor(name: str, obj: Any) -> None:
                if isinstance(obj, h5py.Dataset):
                    available.append(name)

            file.visititems(visitor)
            raise KeyError(
                f"Dataset '{key}' not found. Available datasets: {available}"
            )
        return np.asarray(file[normalized_key][...])


def build_command(
    template: str,
    input_path: Path,
    output_path: Path,
    shape: tuple[int, ...],
    dtype: np.dtype,
) -> list[str]:
    values: dict[str, str | int] = {
        "input": str(input_path),
        "output": str(output_path),
        "size": int(np.prod(shape)),
        "dtype": dtype.name,
    }

    for i, dimension in enumerate(shape):
        values[f"dim{i}"] = dimension

    try:
        command = template.format(**values)
    except KeyError as exc:
        raise ValueError(
            f"Unknown or unavailable placeholder in --cuda-command: {exc}"
        ) from exc

    return shlex.split(command)


def load_raw_output(
    path: Path,
    dtype: np.dtype,
    shape: tuple[int, ...],
) -> np.ndarray:
    if not path.exists():
        raise FileNotFoundError(
            f"CUDA executable did not create the expected output file: {path}"
        )

    array = np.fromfile(path, dtype=dtype)
    expected_size = int(np.prod(shape))

    if array.size != expected_size:
        raise ValueError(
            f"CUDA output contains {array.size} values, but output shape "
            f"{shape} requires {expected_size}. Check --output-dtype, "
            "--output-shape, and the CUDA output format."
        )

    return array.reshape(shape)


def compute_ssim(
    reference: np.ndarray,
    output: np.ndarray,
    data_range: float,
    mode: str,
) -> float:
    if mode == "slice" and reference.ndim >= 3:
        scores = [
            structural_similarity(
                reference[index],
                output[index],
                data_range=data_range,
            )
            for index in range(reference.shape[0])
        ]
        return float(np.mean(scores))

    return float(
        structural_similarity(reference, output, data_range=data_range)
    )


def calculate_metrics(
    reference: np.ndarray,
    output: np.ndarray,
    data_range: float | None,
    ssim_mode: str,
) -> dict[str, Any]:
    if reference.shape != output.shape:
        raise ValueError(
            f"Shape mismatch: reference={reference.shape}, output={output.shape}"
        )

    reference64 = reference.astype(np.float64, copy=False)
    output64 = output.astype(np.float64, copy=False)

    if not np.all(np.isfinite(reference64)):
        raise ValueError("Reference contains NaN or Inf values.")
    if not np.all(np.isfinite(output64)):
        raise ValueError("Output contains NaN or Inf values.")

    difference = output64 - reference64
    mse = float(np.mean(difference ** 2))
    max_error = float(np.max(np.abs(difference)))

    ref_min = float(reference64.min())
    ref_max = float(reference64.max())
    output_min = float(output64.min())
    output_max = float(output64.max())

    if data_range is None:
        data_range = ref_max - ref_min

    if data_range <= 0:
        raise ValueError(
            "Reference data range is zero. Supply --data-range explicitly."
        )

    psnr = (
        math.inf
        if mse == 0
        else float(10.0 * math.log10((data_range ** 2) / mse))
    )

    ssim = compute_ssim(reference64, output64, data_range, ssim_mode)

    return {
        "shape": list(reference.shape),
        "mse": mse,
        "psnr_db": psnr,
        "ssim": ssim,
        "max_absolute_error": max_error,
        "output_min": output_min,
        "output_max": output_max,
        "reference_min": ref_min,
        "reference_max": ref_max,
        "data_range": float(data_range),
    }


def main() -> None:
    args = parse_args()

    reference = load_h5_dataset(args.reference, args.reference_key)

    input_dtype = (
        np.dtype(args.input_dtype)
        if args.input_dtype is not None
        else reference.dtype
    )
    output_dtype = np.dtype(args.output_dtype)
    output_shape = (
        tuple(args.output_shape)
        if args.output_shape is not None
        else tuple(reference.shape)
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)

    if args.keep_input_raw is not None:
        input_path = args.keep_input_raw
        input_path.parent.mkdir(parents=True, exist_ok=True)
        reference.astype(input_dtype, copy=False).tofile(input_path)
        temporary_directory = None
    else:
        temporary_directory = tempfile.TemporaryDirectory(
            prefix="cuda_eval_"
        )
        input_path = Path(temporary_directory.name) / "input.raw"
        reference.astype(input_dtype, copy=False).tofile(input_path)

    command = build_command(
        args.cuda_command,
        input_path,
        args.output,
        tuple(reference.shape),
        input_dtype,
    )

    print("Reference dataset")
    print(f"  File       : {args.reference}")
    print(f"  Dataset    : {args.reference_key}")
    print(f"  Shape      : {reference.shape}")
    print(f"  H5 dtype   : {reference.dtype}")
    print(f"  CUDA input : {input_path}")
    print(f"  Input dtype: {input_dtype}")
    print("\nRunning CUDA command:")
    print("  " + shlex.join(command))

    completed = subprocess.run(command, check=False)

    if completed.returncode != 0:
        raise RuntimeError(
            f"CUDA executable failed with return code {completed.returncode}."
        )

    output = load_raw_output(args.output, output_dtype, output_shape)

    if temporary_directory is not None:
        temporary_directory.cleanup()

    metrics = calculate_metrics(
        reference=reference,
        output=output,
        data_range=args.data_range,
        ssim_mode=args.ssim_mode,
    )

    print("\nEvaluation results")
    print("=" * 52)
    print(f"MSE               : {metrics['mse']:.10g}")
    print(
        "PSNR              : inf dB"
        if math.isinf(metrics["psnr_db"])
        else f"PSNR              : {metrics['psnr_db']:.6f} dB"
    )
    print(f"SSIM              : {metrics['ssim']:.10f}")
    print(f"Max error         : {metrics['max_absolute_error']:.10g}")
    print(f"Output min        : {metrics['output_min']:.10g}")
    print(f"Output max        : {metrics['output_max']:.10g}")
    print(f"Reference min     : {metrics['reference_min']:.10g}")
    print(f"Reference max     : {metrics['reference_max']:.10g}")
    print(f"Created output    : {args.output}")
    print("=" * 52)

    if args.save_json is not None:
        args.save_json.parent.mkdir(parents=True, exist_ok=True)
        with args.save_json.open("w", encoding="utf-8") as file:
            json.dump(metrics, file, indent=2)
        print(f"Saved metrics     : {args.save_json}")


if __name__ == "__main__":
    main()